"""Init

Revision ID: a35e1aae3feb
Revises: 
Create Date: 2020-12-11 22:26:30.613332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35e1aae3feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('chat_tg_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
